# Project information
site_name: "Amar Dhillon's Blog ☕️"
site_description: 'A persanal blog by Amarjit Singh Dhillon'

site_author: 'Amar Dhillon'
site_url: 'https://www.asdhillon.com'

# Repository
repo_name: 'odd-snail/www.asdhillon.com'

# Copyright related
copyright: 'Copyright &copy; 2020  Amarjit Dhillon'

# Configuration
theme:
  name: 'material'      # this is a google material theme
  language: 'en'
  palette:
    primary: 'indigo'   # this is the color for top navigation bar
    accent: 'red'       # this is hover color for links
  # logo: 'resources/logo.svg'  # logo image which is shown at top nav-bar
  # favicon: 'res/favicon.ico'
  feature:
    tabs: true          # changing to true will move the right nav to top nav
  inject_js: true
  # custom_dir: 'custom_theme/'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/odd-snail/'
    - type: 'twitter'
      link: 'https://twitter.com/smartsplash'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/webdexter/'
    - type: 'facebook'
      link: 'https://www.facebook.com/Amar.314/'
    - type: 'instagram'
      link: 'https://www.instagram.com/amarjit_dhillon/'

  disqus: 'amardhillon'

extra_css:
  - 'stylesheets/extra.css' # this is used to customize the material theme; I changed the footer using this


# # Google Analytics
# google_analytics:
#   - 'UA-XXXXXXXX-X'
#   - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      use_pygments: true
      noclasses: false
      pygments_style: vim
      # monokai, rrt ,colorful , vim
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


nav:
  - "Technical":
    - "H2 Database for WSO2 Products": "wso2/h2/index.md"
    - "JMS Queue in WSO2 IoT Server": "wso2/jms/index.md"
    - "Clone private repo into Cpanel": "blogs/gitAndCpanel.md"
    - "Downgrading maven": "maven/downgrade_maven/index.md"
    - "Wget on Mac": "wget/wget.md"
    - "Installing Flink": "installing_flink/flink.md"

    - "Linux": 
      - "Setting Java Home": "linux/java_home/index.md"
      - "Setting andoid device": "linux/android_device.md"
      - "Commands": "linux/commands.md"

    - "MySQL": 
      - "Initial Setup": "mysql/mysql_basics.md"
      - "JDBC Statements": "mysql/JdbcStatements.md" 

  - "Life-Hacks": 
    - "Covid-19 preparedness": "blogs/covidPrep.md"






